import { Metadata } from 'next';
import Image from 'next/image';

import LoginForm from '@/components/LoginForm';

export const metadata: Metadata = {
	title: 'Iniciar sesión',
	description: 'Generated by Next.js'
};

export default function Login() {
	return (
		<section className="bg-gray-50">
			<div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
				<a
					href="http://www.laboratoriossantaines.com/"
					className="bg-white p-5 rounded shadow flex items-center mb-6 text-2xl font-semibold text-gray-900"
				>
					<Image
						width={100}
						height={100}
						className="mr-2"
						src="/img/logo.svg"
						alt="logo"
					/>
					<p className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
						<span className="block uppercase tracking-tighter text-lg">
							Laboratorio Clinico
						</span>
						<span className="text-4xl leading-5 tracking-tight">
							Santa <b className="font-extrabold">Inés</b>
						</span>
					</p>
				</a>
				<div className="w-full bg-white rounded-lg shadow md:mt-0 sm:max-w-md xl:p-0">
					<div className="p-6 space-y-4 md:space-y-6 sm:p-8">
						<h1 className="text-xl font-bold text-gray-900 md:text-2xl">
							Iniciar sesión
						</h1>
						<LoginForm />
					</div>
				</div>
			</div>
		</section>
	);
}
